POST http://localhost:3003/api/users
content-type: application/json

  { "username": "mark", 
    "password": "password123", 
    "name": "mark" }


# DELETE http://localhost:3003/api/blogs/5e9f8ff94357da19b4c28fd8

# PUT http://localhost:3003/api/blogs/5e9f955c04eaab1a42261e9d
# content-type: application/json

# {
#   "url": "facebook.com"
# }

# GET http://localhost:3003/api/users